### PR TITLE
Added swagger Documentation

### PR DESCRIPTION
**Pull request by ferdinandrosario**

### CODE REVIEW

**Comment by dblock** [comment]
Why did you downgrade Grape? That should work with all the latest versions. Also needs tests, something like https://github.com/dblock/grape-on-rack/blob/master/spec/api/documentation_spec.rb. Squash your commits and make sure that the build passes, too.

**Comment by ferdinandrosario** [comment]
I tried to make it work with latest grape 0.11.0 version but Based on the tim-vandecasteele/grape-swagger#187 I downgraded for grape 0.9.0 .
Correct me if i'm doing anything wrong...

**Comment by dblock** [comment]
Everything should work with latest everything, if it doesn't let me help fix it! Write failing specs, PR them here?

**Comment by duffn** [comment]
Closing as stale. Redone in #46.

**Pull request closed without merging**
