### PR TITLE
Add Swagger documentation

### PR DESCRIPTION
**Pull request by duffn**
This adds Swagger documentation and can replace #4.

- Adds Swagger docs using the dist package
- Updates `splines` to add the `reticulated` param for the docs

### CODE REVIEW

**Comment by dblock** [comment]
Looks good, add a rudimentary spec that the swagger documentation loads?

**Comment by duffn** [comment]
Add the spec.

**Review by dblock — COMMENTED** [review]
Good. If you want to add a spec that swagger API actually works you could get inspired from https://github.com/dblock/grape-swagger-rails/blob/1c3d71a27e0c744f470fcb6835250de2a837aedf/spec/features/swagger_spec.rb#L4.

**Comment by duffn** [comment]
I plan to update to update to use `grape-swagger-rails` after I can get that project updated in https://github.com/ruby-grape/grape-swagger-rails/issues/106. I'll add some legitimate tests here when I do that.

**Pull request merged**
